### PR TITLE
[POA-2569] Make common flags as persistent

### PR DESCRIPTION
**Pull request by mudit-postman**
Common flags (forwarded to apidump) do not persist in the subcommand. For example, `agent ec2 --send-witness-payloads` will work, but `agent ec2 setup—-send-witness-payloads` won’t.

Converted the flags to persistentFlags.

### CODE REVIEW

**Comment by mgritter** [comment]
You're going to have to sell me a bit more on this one.  It seems like if we make it persistent, it flows down to all subcommands; is that always what we want?

Can you list the affected commands?

**Comment by mudit-postman** [comment]
Affected commands after making the flags persistent: `ec2 setup`, `ecs add`, `ecs cf-fragment` and `ecs task-def`

Initially, I planned to use the common flags only in subcommands rather than making them persistent. However, in this case, I would have to assign three separate variables for common flag values for three subcommands. Since we would need common flags in all cases (these flags will be forwarded to apidump), I thought to make them persistent.

I will proceed with my initial approach, i.e., add flags to all subcommands separately.

**Comment by mgritter** [comment]
Do they _work_ for ecs cf-fragment and ecs task-def?

What I want to avoid is that the flags are listed as present or accepted for commands where they do not work.  If this makes them work for 'ecs' (implicit add) and they already work for the other commands, that's fine.

**Comment by mudit-postman** [comment]
Yes, we are adding the apidump flags for cf-fragment and task-def. Both of them call the `makeAgentContainerDefinition()` function, which adds the flags to the apidump command.
https://github.com/postmanlabs/postman-insights-agent/blob/cb1d224c210e71d606c06c49eafefc24dcfa36c1/cmd/internal/ecs/add.go#L974-L979

The root command calls the add functions for both `ecs` and `ec2`, so even if the user uses these commands without any subcommand, these will work.
https://github.com/postmanlabs/postman-insights-agent/blob/cb1d224c210e71d606c06c49eafefc24dcfa36c1/cmd/internal/ecs/ecs.go#L44-L52
https://github.com/postmanlabs/postman-insights-agent/blob/cb1d224c210e71d606c06c49eafefc24dcfa36c1/cmd/internal/ec2/ec2.go#L20-L26

**Review by mgritter — APPROVED** [review]

**Pull request merged**
